
AWSTemplateFormatVersion: "2010-09-09"

Description: This is a Banking Application using S3, Lambda and API Gateway

Resources:
  bankingS3Bucket:      # variable for the template
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: accountbalances


  LambdaExecutionRole:  
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: Allow
                  Principal:
                    Service:
                        - lambda.amazonaws.com  #Since lambda is goind to access S3
                  Action:
                    - 'sts:AssumeRole'  #To Temporarily access S3
        Description: IAM Role for Lambda to Access S3
        ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess # from IAM Policies of S3FullAccess
        RoleName: LambdaexecutionRole   # Role Name
